export const WIDGET_IFRAME_READY = 'WIDGET_IFRAME_READY';
export const WIDGET_RENDERED = 'WIDGET_RENDERED';
export const WIDGET_POPUP_OPEN = 'WIDGET_POPUP_OPEN';
export const WIDGET_POPUP_CLOSE = 'WIDGET_POPUP_CLOSE';
export const WIDGET_POPUP_TOGGLE = 'WIDGET_POPUP_TOGGLE';
export const SCREENSHOT_REQUEST_SUCCESS = 'SCREENSHOT_REQUEST_SUCCESS';
export const SCREENSHOT_REQUEST_ERROR = 'SCREENSHOT_REQUEST_ERROR';
