export const UNREAD_MESSAGES_CHANGE = 'UNREAD_MESSAGES_CHANGE';
export const UNREAD_REPLIES_CHANGE = 'UNREAD_REPLIES_CHANGE';

export const JOIN_ROOM = 'JOIN_ROOM';
export const JOIN_ROOM_ERROR = 'JOIN_ROOM_ERROR';

export const OPERATOR_ONLINE_STATUS_CHANGE = 'OPERATOR_ONLINE_STATUS_CHANGE';
export const OPERATOR_ONLINE_STATUS_SUBSCRIBE = 'OPERATOR_ONLINE_STATUS_SUBSCRIBE';
export const OPERATOR_ONLINE_STATUS_SUBSCRIBE_ABORT = 'OPERATOR_ONLINE_STATUS_SUBSCRIBE_ABORT';

export const TYPING_STATUS_CHANGE = 'TYPING_STATUS_CHANGE';
export const TYPING_STATUS_SUBSCRIBE = 'TYPING_STATUS_SUBSCRIBE';
export const TYPING_STATUS_SUBSCRIBE_ERROR = 'TYPING_STATUS_SUBSCRIBE_ERROR';
