export const UNREAD_MESSAGES_CHANGE = 'UNREAD_MESSAGES_CHANGE';
export const UNREAD_REPLIES_CHANGE = 'UNREAD_REPLIES_CHANGE';
export const LAST_READ_MESSAGE_CHANGE = 'LAST_READ_MESSAGE_CHANGE';
export const UNREAD_MESSAGES_SUBSCRIBE_SUCCESS = 'UNREAD_MESSAGES_SUBSCRIBE_SUCCESS';
export const UNREAD_MESSAGES_SUBSCRIBE_ERROR = 'UNREAD_MESSAGES_SUBSCRIBE_ERROR';
export const UNREAD_FETCH_COUNTS_SUCCESS = 'UNREAD_FETCH_COUNTS_SUCCESS';
export const UNREAD_FETCH_COUNTS_ERROR = 'UNREAD_FETCH_COUNTS_ERROR';

export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';
export const JOIN_ROOM_ERROR = 'JOIN_ROOM_ERROR';

export const INITIALIZATION_SUCCESS = 'INITIALIZATION_SUCCESS';
// export const INITIALIZATION_ERROR = 'INITIALIZATION_ERROR';

export const OPERATOR_ONLINE_STATUS_CHANGE = 'OPERATOR_ONLINE_STATUS_CHANGE';
export const OPERATOR_ONLINE_STATUS_SUBSCRIBE_SUCCESS = 'OPERATOR_ONLINE_STATUS_SUBSCRIBE_SUCCESS';
export const OPERATOR_ONLINE_STATUS_SUBSCRIBE_ERROR = 'OPERATOR_ONLINE_STATUS_SUBSCRIBE_ERROR';

export const TYPING_STATUS_CHANGE = 'TYPING_STATUS_CHANGE';
export const TYPING_STATUS_SUBSCRIBE_SUCCESS = 'TYPING_STATUS_SUBSCRIBE_SUCCESS';
export const TYPING_STATUS_SUBSCRIBE_ERROR = 'TYPING_STATUS_SUBSCRIBE_ERROR';

// export const MESSAGES_SUBSCRIBE_SUCCESS = 'MESSAGES_SUBSCRIBE_SUCCESS';
// export const MESSAGES_SUBSCRIBE_ERROR = 'MESSAGES_SUBSCRIBE_ERROR';

export const MESSAGES_HISTORY_SET = 'MESSAGES_HISTORY_SET';
export const MESSAGES_HISTORY_APPEND_ONE = 'MESSAGES_HISTORY_APPEND_ONE';
// export const MESSAGES_HISTORY_APPEND_MANY = 'MESSAGES_HISTORY_APPEND_MANY';

// export const MESSAGES_HISTORY_PREPEND_ONE = 'MESSAGES_HISTORY_PREPEND_ONE';
export const MESSAGES_HISTORY_PREPEND_MANY = 'MESSAGES_HISTORY_PREPEND_MANY';

export const MESSAGES_HISTORY_CHANGE_ONE = 'MESSAGES_HISTORY_CHANGE_ONE';
export const MESSAGES_HISTORY_CHANGE_MANY = 'MESSAGES_HISTORY_CHANGE_MANY';

export const MESSAGES_FETCH_HISTORY_SUCCESS = 'MESSAGES_FETCH_HISTORY_SUCCESS';
export const MESSAGES_FETCH_HISTORY_INITIAL_SUCCESS = 'MESSAGES_FETCH_HISTORY_INITIAL_SUCCESS';
export const MESSAGES_FETCH_HISTORY_ERROR = 'MESSAGES_FETCH_HISTORY_ERROR';
export const MESSAGES_FETCH_HISTORY_INITIAL_ERROR = 'MESSAGES_FETCH_HISTORY_INITIAL_ERROR';

export const UPDATE_MESSAGES_SUBSCRIBE_SUCCESS = 'UPDATE_MESSAGES_SUBSCRIBE_SUCCESS';
export const UPDATE_MESSAGES_SUBSCRIBE_ERROR = 'UPDATE_MESSAGES_SUBSCRIBE_ERROR';
export const UPDATE_MESSAGES_CHANGE = 'UPDATE_MESSAGES_CHANGE';
