export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';
export const JOIN_ROOM_ERROR = 'JOIN_ROOM_ERROR';

export const MESSAGES_HISTORY_PREPEND = 'MESSAGES_HISTORY_PREPEND';
export const MESSAGES_HISTORY_CHANGE = 'MESSAGES_HISTORY_CHANGE';
export const MESSAGES_RECEIVE = 'MESSAGES_RECEIVE';
export const MESSAGES_RETRIEVE_LAST_MESSAGE_CURSOR = 'MESSAGES_RETRIEVED_LAST_MESSAGE_CURSOR';

export const TYPING_STATUS_CHANGE = 'TYPING_STATUS_CHANGE';
export const TYPING_STATUS_SUBSCRIBE_SUCCESS = 'TYPING_STATUS_SUBSCRIBE_SUCCESS';
export const TYPING_STATUS_SUBSCRIBE_ERROR = 'TYPING_STATUS_SUBSCRIBE_ERROR';

export const UNREAD_COUNTER_LAST_READ_MESSAGE_CHANGE = 'UNREAD_COUNTER_LAST_READ_MESSAGE_CHANGE';
export const UNREAD_COUNTER_MESSAGES_CHANGE = 'UNREAD_COUNTER_MESSAGES_CHANGE';
export const UNREAD_COUNTER_REPLIES_CHANGE = 'UNREAD_COUNTER_REPLIES_CHANGE';
export const UNREAD_COUNTER_NOTIFY_ABOUT_NEW_REPLIES = 'UNREAD_COUNTER_NOTIFY_ABOUT_NEW_REPLIES';

export const UPDATE_MESSAGE_SUBSCRIPTION_CHANGE_MESSAGE = 'UPDATE_MESSAGE_SUBSCRIPTION_CHANGE_MESSAGE';
export const ONLINE_STATUS_CHANGE = 'ONLINE_STATUS_CHANGE';
export const ERROR_ALERT = 'ERROR_ALERT';
